CREATE TABLE learners (
    id text PRIMARY KEY,
    telegram_id bigint UNIQUE CHECK (telegram_id > 0),
    display_name text NOT NULL DEFAULT '',
    status text NOT NULL CHECK (status IN ('active','pending','rejected','revoked')),
    generation integer NOT NULL DEFAULT 1 CHECK (generation > 0),
    joined_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (id <> 'owner' OR (status = 'active' AND telegram_id IS NULL))
);
INSERT INTO learners(id, status) VALUES ('owner', 'active');

ALTER TABLE coach_state DROP CONSTRAINT coach_state_id_check;
ALTER TABLE coach_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
ALTER TABLE coach_state ADD COLUMN learner_id text NOT NULL DEFAULT 'owner' REFERENCES learners(id);
ALTER TABLE coach_state ADD CONSTRAINT coach_state_learner_key UNIQUE (learner_id);

ALTER TABLE jobs ADD COLUMN learner_id text NOT NULL DEFAULT 'owner' REFERENCES learners(id);
ALTER TABLE jobs ADD COLUMN access_generation integer NOT NULL DEFAULT 1;
CREATE INDEX jobs_learner_ready ON jobs(learner_id, status, available_at);

ALTER TABLE outbox ADD COLUMN learner_id text NOT NULL DEFAULT 'owner' REFERENCES learners(id);
ALTER TABLE outbox ADD COLUMN access_generation integer NOT NULL DEFAULT 1;
ALTER TABLE outbox ADD COLUMN access_notice boolean NOT NULL DEFAULT false;
CREATE INDEX outbox_learner_ready ON outbox(learner_id, status, available_at);

ALTER TABLE task_keys ADD COLUMN learner_id text NOT NULL DEFAULT 'owner' REFERENCES learners(id);
ALTER TABLE task_keys DROP CONSTRAINT task_keys_pkey;
ALTER TABLE task_keys DROP CONSTRAINT task_keys_origin_key;
ALTER TABLE task_keys ADD PRIMARY KEY (learner_id, id);
ALTER TABLE task_keys ADD UNIQUE (learner_id, origin);

ALTER TABLE answer_keys ADD COLUMN learner_id text NOT NULL DEFAULT 'owner' REFERENCES learners(id);
ALTER TABLE answer_keys DROP CONSTRAINT answer_keys_pkey;
ALTER TABLE answer_keys ADD PRIMARY KEY (learner_id, session_id, question_id);

CREATE TABLE invitations (
    id text PRIMARY KEY,
    token_hash text UNIQUE NOT NULL,
    label text NOT NULL DEFAULT '',
    status text NOT NULL CHECK (status IN ('open','claimed','cancelled')),
    claimed_by text REFERENCES learners(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

CREATE TABLE telegram_receipts (
    update_id bigint PRIMARY KEY,
    learner_id text REFERENCES learners(id),
    disposition text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE access_audit (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    update_id bigint NOT NULL REFERENCES telegram_receipts(update_id),
    action text NOT NULL,
    subject_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ai_usage (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    learner_id text NOT NULL REFERENCES learners(id),
    job_id text NOT NULL REFERENCES jobs(id),
    operation text NOT NULL,
    local_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ai_usage_daily ON ai_usage(learner_id, local_date);

INSERT INTO schema_migrations(version) VALUES (2);
